export interface Contrato {
    // ? no requerido
    id_contrato?: number,
    numero_contrato: string,
    fecha_suscripcion: Date,
    naturaleza_del_contrato: string,
    caracteristica: string,
    partei: string,
    parteii: string,
    termino_pago: string,
    termino_aceptar : number,
    termino_vigencia : string,
    termino_reclamacion : number,
    termino_contestar : number,
    fecha_culminacion: any,
    ubicacion: number,
    dictamen_tecnico : string,
    responsable : number,
    observaciones: string,
    contraparte: string,
    en_calle : boolean,
    falta_contrato : boolean,
    cce : number,
}
